export const SHARED_PREFERENCES = {
  CONFIRM_BEFORE_SENDING: false,
  CONFIRM_BEFORE_REMOVING: true,
  CONFIRM_BEFORE_FILING: true,

  MAIL_SHOW_BUTTON_SYNC: true,
  MAIL_SHOW_BUTTON_CLEAN: false,
  MAIL_SHOW_BUTTON_SEARCH: true,

  MAIL_SHOW_BUTTON_UN_READ: true,
  MAIL_SHOW_BUTTON_REMOVE: false,
  MAIL_SHOW_BUTTON_ARCHIVE: false,

  DB: { DI: 'DATABASE_INBOX', DS: 'DATABASE_SENT' },

  inbox: {
    MAIL_SHOW_BUTTON_SYNC: true,
    MAIL_SHOW_BUTTON_CLEAN: false,
    MAIL_SHOW_BUTTON_SEARCH: true,
  },
  create: {
    CONFIRM_BEFORE_SENDING: false,
    CONFIRM_BEFORE_REMOVING: true,
    CONFIRM_BEFORE_FILING: true,
  },
  detail: {
    MAIL_SHOW_BUTTON_UN_READ: true,
    MAIL_SHOW_BUTTON_REMOVE: true,
    MAIL_SHOW_BUTTON_ARCHIVE: true,
    CONFIRM_BEFORE_REMOVING: true,
  },
  general: {
    DB: { DI: 'DATABASE_INBOX', DS: 'DATABASE_SENT' },
  },
}
