export const SHARED_PREFERENCE = {
  CONFIRM_BEFORE_SENDING: false,
  CONFIRM_BEFORE_REMOVING: true,
  CONFIRM_BEFORE_FILING: true,

  MAIL_SHOW_BUTTON_SYNC: true,
  MAIL_SHOW_BUTTON_CLEAN: false,
  MAIL_SHOW_BUTTON_SEARCH: true,

  MAIL_SHOW_BUTTON_UN_READ: true,
  MAIL_SHOW_BUTTON_REMOVE: false,
  MAIL_SHOW_BUTTON_ARCHIVE: false,

  DB: { DI: 'DATABASE_INBOX', DS: 'DATABASE_SENT' },
};
