export const SHARED_PREFERENCE = {
    CONFIRM_BEFORE_SENDING: true,
    CONFIRM_BEFORE_REMOVING: true,
    CONFIRM_BEFORE_FILING: true,
    MAIL_SHOW_BUTTON_SYNC: true,
    MAIL_SHOW_BUTTON_CLEAN: true,
    MAIL_SHOW_BUTTON_SEARCH: true,
    MAIL_SHOW_BUTTON_UN_READ: true,
    MAIL_SHOW_BUTTON_REMOVE: true,
    MAIL_SHOW_BUTTON_ARCHIVE: true,
    DB: {DI: "DATABASE_INBOX", DS: "DATABASE_SENT"}
};